#!/bin/bash

# env GOOS=linux GOARCH=arm GOARM=5 go build && scp ./oilmeter pi@raspberry2:Gasoleo
# env GOOS=linux GOARCH=arm GOARM=5 go build && cp oilmeter ~/Dropbox/Gasoleo/

./build && ssh pi@caldera pkill caldera && scp ./caldera pi@caldera:Local && scp -r ./web pi@caldera:.
